version: "3"
services:
  proxy:
    container_name: "proxy"
    build:
      context: "./proxy/"
      dockerfile: "Dockerfile"
    ports:
      - "443:443"
      environment:
        - AUTHORIZED_TEAMS=3391844,273957
  demo-app:
    container_name: "demo-app"
    image: httpd:latest
    ports:
      - "80:80"
