version: "3"
services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy/
      dockerfile: Dockerfile
      args:
        TARGET_HOST: ${APP_NAME}:${APP_PORT}
    ports:
      - 443:443
    environment:
      - AUTHORIZED_TEAMS=${AUTHORIZED_TEAMS}
  web_app:
    container_name: ${APP_NAME}
    image: httpd:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
